<?php

namespace fanouu\GameManager\packets;

use fanouu\GameManager\packets\handlers\PacketHandler;
use fanouu\GameManager\servers\GameServer;

class UpdatePlayerStatus extends Packet
{

    const NONE_STATUS = 0;
    const IN_GAME_STATUS = 2;
    const REMOVE_IN_GAME = 3;
    const SET_IN_GAME_STATUS = 4;

    public int $packet_id = PacketId::UPDATEPLAYERSTATUS;

    public int $status = 0;
    public array $extraData;

    public string $player_name = "";

    public function decodePayload(): void
    {
        $this->status = $this->getInt();
        $this->extraData = json_decode($this->getString(), true);
        $this->player_name = $this->getString();
    }

    public function encodePayload(): void
    {
        parent::encodePayload(); // TODO: Change the autogenerated stub
    }

    public function handle(PacketHandler $gamePacketHandler, GameServer $gameServer): void
    {
        $gamePacketHandler->updatePlayerStatus($this, $gameServer);
    }
}